// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function GetSettings():Promise<config.Config>;

export function SaveSettings(arg1:config.Config):Promise<void>;

export function TogglePause():Promise<boolean>;
